"""Classification rules that decide what a stored value is allowed to claim.

An Agent application's log says where a value came from; it does not say what
the value proves.  Every visible agent reply arrives on the same channel as a
result, every tool call that did not report an error looks like a passing
check, and text an application injects into the user's turn arrives with the
user's role.  If those distinctions are not drawn at ingest, they cannot be
drawn later, and a report ends up stating things that are not true.

This module owns those rules for every adapter, so ``message`` /
``agent_message``, ``tool_calls`` / ``verifications`` and
``content_completeness`` / ``provenance_trimmed`` mean the same thing
regardless of which application produced the turn.  It reads no files and
writes nothing.
"""

from __future__ import annotations

import json
import re
import shlex
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple


# Text an Agent application injects into the user's turn.  It arrives with the
# user's transport role, but the person did not write it and a report must not
# quote it as intent.
_INJECTED_PREFIXES = (
    "<recommended_plugins>",
    "<environment_context>",
    "<turn_aborted>",
    "<file_context>",
    "<skill>",
    "<system-reminder>",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<user-prompt-submit-hook>",
)
_INJECTED_PATTERNS = (
    re.compile(r"^\[Request interrupted by user"),
    re.compile(r"^\[Request cancelled"),
    re.compile(r"^Caveat: The messages below were generated by the user while running"),
    re.compile(r"^The following is the .{0,60}agent history\b"),
    re.compile(r"^# AGENTS\.md instructions for "),
    re.compile(r"^# AGENTS\.md instructions\r?\n\r?\n<INSTRUCTIONS>"),
    re.compile(r"^# Files mentioned by the user:"),
    re.compile(r"^<codex_internal_context"),
    re.compile(r"^# Applications mentioned by the user:"),
    re.compile(r"^\[Slock inbox notice:"),
    re.compile(r"^<subagent_notification>"),
)
# A queued message the UI re-submits verbatim on the next turn.
_RESUBMIT_PREFIX = "↪"

# Targets are harvested from any tool payload key that looks like a path, so
# screenshot caches and opaque handles arrive next to real edits.
_NOISE_TARGET_PATTERNS = (
    re.compile(r"/\.SmartWork/cache/"),
    re.compile(r"/screenshots?/"),
    re.compile(r"^/private/(?:tmp|var)/"),
    re.compile(r"^/tmp/"),
    re.compile(r"^/var/folders/"),
    re.compile(r"/__pycache__/"),
    re.compile(r"^/Users/[^/]+/Library/Caches/"),
)
_UUID = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
# Delegation tools contribute their sub-agent's name, which looks nothing like
# a file but cannot be proven not to be one (``Makefile``).  Such values are
# separated rather than discarded.
_PATH_LIKE = re.compile(r"[/\\]|\.[A-Za-z0-9]{1,8}$|^[A-Za-z]:")

# Tool names whose "passed" means a verification actually ran.  Everything
# else only means the tool was invoked and reported no error.
_VERIFYING_TOOLS = frozenset({
    "test", "tests", "pytest", "unittest", "test_result", "check_result",
    "lint", "lint_result", "lints", "typecheck", "mypy", "ruff", "eslint",
    "build", "compile", "compileall",
})
_VERIFYING_COMMANDS = frozenset({
    "pytest", "unittest", "mypy", "ruff", "eslint", "tsc", "jest",
    "vitest", "flake8", "pylint", "shellcheck", "compileall", "tox",
    "nox", "rspec",
})
_VERIFYING_INTERPRETERS = frozenset({
    "python", "python3", "node", "groovy", "ruby", "perl", "sh", "bash",
    "zsh", "deno", "bun",
})
_VERIFYING_SCRIPT_WORDS = frozenset({
    "test", "tests", "spec", "specs", "check", "checks", "verify", "lint",
    "typecheck",
})
# Multi-word runners, matched only in command position.  ``python -m pytest``
# needs no entry here because ``pytest`` is itself a verifying command.
_VERIFYING_PHRASES = (
    "npm test", "npm run test", "yarn test", "pnpm test", "go test",
    "cargo test", "make test", "make lint", "make check", "mvn test",
    "dotnet test", "swift test",
)
# Commands whose output is ordinarily inspection rather than a change or a
# verification.  The vocabulary is intentionally narrow; a command outside
# it is substantive because the classifier cannot prove its effect.
_READ_ONLY_COMMANDS = frozenset({
    "sed", "nl", "rg", "cat", "head", "tail", "wc", "ls", "find", "grep",
    "less", "file", "stat", "tree", "du", "pwd", "echo", "printf", "which",
    "type", "jq", "column", "sort", "uniq", "cut", "awk", "diff", "basename",
    "dirname", "realpath", "readlink",
})
# A read-oriented utility can still mutate when a known write form is present.
# Keep these checks command-specific: treating every option as suspicious would
# turn harmless inspection flags into false work, while accepting these forms
# would silently omit real work from an explicitly aborted turn.
_READ_ONLY_WRITE_FORMS = {
    "sed": frozenset({"--in-place"}),
    "find": frozenset({
        "-delete", "-exec", "-execdir", "-ok", "-okdir",
        "-fprint", "-fprint0", "-fprintf", "-fls",
    }),
    "sort": frozenset({"-o", "--output"}),
    "awk": frozenset({"--inplace"}),
}
_ASSIGNMENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
_SHELL_SYNTAX = re.compile(r"[\s;&|()<>$]")
_INSTALLERS = frozenset({
    "pip", "pip3", "npm", "pnpm", "yarn", "brew", "apt", "apt-get", "uv",
    "poetry", "gem", "bundle", "go", "cargo", "dotnet", "conda", "mamba",
})
_INSTALL_VERBS = frozenset({"install", "add", "ci", "get"})
_BARE_FAILURE = re.compile(r"^[A-Za-z0-9_]+$")
# Adapter fallbacks use these short labels when the source did not expose a
# useful error payload.  They are not information-bearing failures and must
# not keep an explicitly aborted, otherwise empty turn alive.
_NON_INFORMATIVE_FAILURES = frozenset({
    "error",
    "failed",
    "failure",
    "tool failure",
    "unknown failure",
    "unknown error",
})
_UNTITLED_TITLES = frozenset({"未命名会话", "untitled", "new chat", "新会话"})
_MAX_TITLE_LENGTH = 120

# Stopping a turn on purpose is not a failure of the work.
_INTERRUPT_MARKERS = frozenset({
    "interrupted", "turn_aborted", "aborted", "cancelled", "canceled",
})

# Warning codes that mean conversation content is genuinely missing.
#
# ``unknown_record_type`` belongs here only because every record type the
# adapters actually see is now classified.  If it fires, the source emitted
# something new and the turn really may be incomplete -- which is the signal
# worth having, and the reason the deliberately-dropped types were moved into
# the noise table rather than excused here.
CONTENT_LOSS_CODES = frozenset({
    "incomplete",
    "incomplete_turn",
    "incomplete_tail",
    "orphan_branch",
    "source_contains_malformed_record",
    "missing_event_timestamp",
    "invalid_record",
    "source_unavailable",
    "unknown_record_type",
})
# Codes that only mean fewer pointers or list items were stored than were seen.
_PROVENANCE_TRIM_SUFFIX = "_omitted"


def warning_code(value: Any) -> str:
    """Return the leading code of a warning, which may be text or an object."""

    if isinstance(value, Mapping):
        return str(value.get("code") or "warning")
    text = str(value)
    return text.split(" ", 1)[0].split(":", 1)[0]


def is_injected_text(value: Any) -> bool:
    """True when text is an application's own scaffolding, whoever carries it.

    ``classify_origin`` answers this only for a block holding the person's
    transport role.  The same scaffolding also arrives in containers that have
    no role at all -- a delegation's ``task`` is the injected prompt its
    sub-agent was handed -- and those need the shape test without the role
    test.
    """

    text = str(value or "").strip()
    if not text:
        return False
    if text.startswith(_INJECTED_PREFIXES) or text.startswith(_RESUBMIT_PREFIX):
        return True
    return any(pattern.match(text) for pattern in _INJECTED_PATTERNS)


def classify_origin(author_role: Any, text: Any) -> str:
    """Return who actually produced a block's text.

    ``user``, ``agent`` or ``system_injected``.  Only ``user`` may be quoted
    as the person's own words.
    """

    if str(author_role or "") != "self":
        return "agent"
    value = str(text or "").strip()
    if not value:
        return "user"
    return "system_injected" if is_injected_text(value) else "user"


def is_noise_target(value: Any) -> bool:
    """True when a target is a cache artefact or an opaque handle."""

    text = str(value).strip()
    if not text:
        return True
    if _UUID.match(text):
        return True
    return any(pattern.search(text) for pattern in _NOISE_TARGET_PATTERNS)


def partition_targets(values: Iterable[Any]) -> Tuple[List[str], List[str], int]:
    """Split raw targets into changed files, other targets and dropped noise."""

    changed: List[str] = []
    other: List[str] = []
    dropped = 0
    for value in values:
        text = str(value)
        if is_noise_target(text):
            dropped += 1
            continue
        target = changed if _PATH_LIKE.search(text) else other
        if text not in target:
            target.append(text)
    return changed, other, dropped


def _partition_other_targets(values: Iterable[Any]) -> Tuple[List[str], int]:
    """Keep extracted non-change targets out of the path-based change bucket."""

    other: List[str] = []
    dropped = 0
    for value in values:
        text = str(value)
        if is_noise_target(text):
            dropped += 1
            continue
        if text not in other:
            other.append(text)
    return other, dropped


def _basename(token: str) -> str:
    return re.split(r"[/\\]", token)[-1]


def _shell_command_segments(value: str) -> List[str]:
    """Split a shell-shaped label without treating quoted separators as code."""

    segments: List[str] = []
    current: List[str] = []
    quote: Optional[str] = None
    escaped = False
    for character in value:
        if escaped:
            current.append(character)
            escaped = False
            continue
        if character == "\\" and quote != "'":
            current.append(character)
            escaped = True
            continue
        if quote:
            current.append(character)
            if character == quote:
                quote = None
            continue
        if character in {"'", '"'}:
            quote = character
            current.append(character)
            continue
        if character in ";&|()":
            if current:
                segments.append("".join(current))
                current = []
            continue
        current.append(character)
    if current:
        segments.append("".join(current))
    return segments


def _command_position_basenames(value: str) -> Iterable[str]:
    for segment in _shell_command_segments(value):
        words = segment.split()
        while words and _ASSIGNMENT.match(words[0]):
            words = words[1:]
        if words:
            yield _basename(words[0].strip("\"'"))


def is_read_only_check(value: Any) -> bool:
    """True when every command segment is provably read-only.

    A compound command is read-only only when all of its segments are known
    inspection utilities.  Unknown commands, redirects and shell expansion
    stay substantive because the classifier cannot prove they had no effect.
    """

    text = str(value).strip()
    label, separator, _status = text.rpartition(":")
    label = (label if separator else text).strip()
    if not label:
        return False
    if any(char in label for char in "<>$()`"):
        return False
    segments = _shell_command_segments(label)
    if not segments:
        return False
    proven = 0
    for segment in segments:
        try:
            words = shlex.split(segment, posix=True)
        except ValueError:
            # Malformed quoting is not proof of a harmless command.
            return False
        while words and _ASSIGNMENT.match(words[0]):
            words = words[1:]
        if not words:
            return False
        basename = _basename(words[0].strip("\"'"))
        if basename not in _READ_ONLY_COMMANDS:
            return False
        options = _READ_ONLY_WRITE_FORMS.get(basename, frozenset())
        for token in words[1:]:
            option = token.strip("\"'")
            if basename == "sed":
                # ``-ni`` and ``-i.bak`` are common compact/backup spellings.
                if option.startswith("--in-place") or (
                    option.startswith("-")
                    and not option.startswith("--")
                    and "i" in option[1:]
                ):
                    return False
            elif basename == "awk":
                if option == "-i" or option.startswith("--inplace"):
                    return False
            elif basename == "sort":
                # GNU/BSD sort accept both ``-o FILE`` and compact ``-oFILE``.
                if (
                    option in options
                    or option.startswith("--output=")
                    or (option.startswith("-o") and len(option) > 2)
                ):
                    return False
            elif option in options or any(
                option.startswith(f"{known}=") for known in options
            ):
                return False
        proven += 1
    return proven == len(segments)


def _is_verifying_script_position(tokens: Sequence[str]) -> bool:
    """Match a verification-like word only in the command/script slot."""

    if not tokens:
        return False
    command = tokens[0]
    if _basename(command) in _VERIFYING_INTERPRETERS:
        if len(tokens) < 2:
            return False
        script = tokens[1]
    elif command.startswith("./") or command.startswith("/"):
        script = command
    else:
        return False
    name = _basename(script)
    stem = name.rsplit(".", 1)[0] if "." in name else name
    return any(word in _VERIFYING_SCRIPT_WORDS for word in re.split(r"[-_.]", stem))


def is_verifying_check(value: Any) -> bool:
    """True when a check names a real test, lint or build rather than a call.

    A check label is either a tool name or a shell command, and the two need
    different rules.  ``_VERIFYING_TOOLS`` holds bare words like ``test`` and
    ``build`` because that is what an MCP-style tool is called -- but the same
    words are ordinary shell utilities, so applying the name rule to a command
    reads ``test -f config.yaml`` as a passing test suite.  A tool name never
    contains whitespace or shell syntax, so that is the discriminator, and
    exactly one of the two rules is applied.
    """

    text = str(value).strip()
    label, separator, _status = text.rpartition(":")
    label = (label if separator else text).strip().lower()
    if not label:
        return False
    if not _SHELL_SYNTAX.search(label) and not label.startswith(("./", "/")):
        if label in _VERIFYING_TOOLS:
            return True
        return re.split(r"[/\\]", label, maxsplit=1)[0] in _VERIFYING_TOOLS
    for segment in re.split(r";|&&|\|\||\||\(|\)", label):
        words = segment.split()
        # ``FOO=1 swift test`` runs a test suite; the assignment is not the
        # command.
        while words and _ASSIGNMENT.match(words[0]):
            words = words[1:]
        # A word wrapped in its own quotes is data the command was given, not
        # a command: ``rg -n 'test.sh|ci_swift_test'`` searched for a test
        # script rather than running one.
        tokens = [
            word.strip("\"'") for word in words
            if not (len(word) > 1 and word[0] in "\"'" and word[-1] == word[0])
        ]
        tokens = [word for word in tokens if word]
        if not tokens:
            continue
        # ``pip3 install mypy ruff`` names two checkers and runs neither.  An
        # installer segment is judged on its own and never lends its argument
        # names to the command as a whole.
        if _basename(tokens[0]) in _INSTALLERS and tokens[1:2] and tokens[1] in _INSTALL_VERBS:
            continue
        # A phrase only counts in command position.  ``echo "make test"``
        # printed the words; it did not run the target.
        head = " ".join([_basename(tokens[0])] + tokens[1:3])
        if any(head.startswith(phrase) for phrase in _VERIFYING_PHRASES):
            return True
        if _is_verifying_script_position(tokens):
            return True
        if any(_basename(token) in _VERIFYING_COMMANDS for token in tokens):
            return True
    return False


def normalize_title(value: Any) -> Optional[str]:
    """Return a bounded readable session title or ``None`` for placeholders."""

    if value is None:
        return None
    title = " ".join(str(value).split())
    if not title or title.casefold() in _UNTITLED_TITLES:
        return None
    return title[:_MAX_TITLE_LENGTH]


def is_user_interrupt(value: Any) -> bool:
    """True when a recorded failure is the person deliberately stopping."""

    return str(value).strip().lower() in _INTERRUPT_MARKERS


def _is_bare_failure(text: str) -> bool:
    normalized = " ".join(text.strip().casefold().split())
    if normalized in _NON_INFORMATIVE_FAILURES:
        return True
    return len(text) < 25 and bool(_BARE_FAILURE.fullmatch(text))


def build_execution_evidence(
    *,
    changed_targets: Iterable[Any] = (),
    other_targets: Iterable[Any] = (),
    checks: Iterable[Any] = (),
    failures: Iterable[Any] = (),
    omitted_count: int = 0,
) -> Dict[str, Any]:
    """Turn raw tool observations into claims that can each be defended."""

    changed, other, dropped = partition_targets(changed_targets)
    explicit_other, other_dropped = _partition_other_targets(other_targets)
    for target in explicit_other:
        if target not in changed and target not in other:
            other.append(target)
    tool_calls: List[str] = []
    verifications: List[str] = []
    for value in checks:
        text = str(value)
        target = verifications if is_verifying_check(text) else tool_calls
        if text not in target:
            target.append(text)
    real_failures: List[str] = []
    interrupts: List[str] = []
    dropped_failures = 0
    for value in failures:
        text = str(value)
        if is_user_interrupt(text):
            if text not in interrupts:
                interrupts.append(text)
        elif _is_bare_failure(text):
            dropped_failures += 1
        elif text not in real_failures:
            real_failures.append(text)
    return {
        "changed_targets": changed,
        "other_targets": other,
        "tool_calls": tool_calls,
        "verifications": verifications,
        "failures": real_failures,
        "user_interrupts": interrupts,
        "omitted_count": int(omitted_count) + dropped + other_dropped + dropped_failures,
    }


def has_substantive_result(
    evidence: Mapping[str, Any],
    *,
    successful_commands: Iterable[Any] = (),
    completed_delegations: Iterable[Mapping[str, Any]] = (),
) -> bool:
    """Return whether a turn contains observable work worth retaining.

    User prose, abort markers and pure reads do not qualify.  Unknown command
    syntax is retained as substantive evidence because absence of proof is not
    proof of a read-only operation.
    """

    if any(str(value).strip() for value in evidence.get("changed_targets") or []):
        return True
    if any(str(value).strip() for value in evidence.get("verifications") or []):
        return True
    if any(str(value).strip() for value in evidence.get("failures") or []):
        return True
    for value in successful_commands:
        text = str(value).strip()
        if text and not is_read_only_check(text):
            return True
    for delegation in completed_delegations:
        if not isinstance(delegation, Mapping):
            continue
        status = str(delegation.get("status") or "").lower()
        result = str(delegation.get("result") or "").strip()
        if status == "complete" and result:
            return True
    return False


def classify_warnings(warnings: Sequence[Any], *, source_corrupt: bool = False) -> Dict[str, Any]:
    """Decide completeness and trimming from the warnings a turn produced.

    A single ``coverage`` value used to collapse these, which made roughly
    half of all turns read as degraded for reasons that cost a reader nothing.
    """

    content_reasons: List[str] = []
    trim_reasons: List[str] = []
    for warning in warnings:
        code = warning_code(warning)
        if code in CONTENT_LOSS_CODES:
            content_reasons.append(code)
        elif code.endswith(_PROVENANCE_TRIM_SUFFIX):
            trim_reasons.append(code)
    if source_corrupt or "source_contains_malformed_record" in content_reasons:
        completeness = "truncated"
    elif content_reasons:
        completeness = "partial"
    else:
        completeness = "complete"
    return {
        "content_completeness": completeness,
        "provenance_trimmed": bool(trim_reasons),
        "content_loss_reasons": sorted(set(content_reasons)),
        "provenance_trim_reasons": sorted(set(trim_reasons)),
    }


# -- reading a stored slice -------------------------------------------------
#
# A schema 2 slice already carries honest names, so these helpers only select;
# they never rename or reinterpret.


# The fixed schema Codex's approval reviewer answers with.  It is the reply to
# the injected "agent history whose request action you are assessing" prompt,
# so the assessed action is already recorded in the conversation that ran it,
# and the verdict itself states the mechanism's opinion rather than a fact
# about the work.  Recognising it only labels a suppression the general rule
# (no prose, no evidence) has already decided -- a schema that drifts costs a
# label, never a dropped activity.
_VERDICT_KEYS = frozenset({"risk_level", "user_authorization", "outcome", "rationale"})
# The reviewer also answers tersely.  Measured across the corpus: 5,501
# records carry the full four keys, 3,162 carry ``outcome`` alone and 42 carry
# a two- or three-key subset -- and every one of the 3,204 terse values is
# ``allow``.  So the shape is "a subset of this vocabulary, including the
# verdict itself", which a tool result carrying its own fields cannot satisfy.
# The same verdict also arrives wrapped in a markdown fence.  Unwrapping is
# done here rather than in ``_is_json_line`` because that one classifies a
# single line for prose detection, where a fence is already its own signal.
_FENCED_JSON = re.compile(r"\A```(?:json)?\s*\n(?P<body>.*?)\n?```\Z", re.DOTALL)


def is_approval_verdict(value: Any) -> bool:
    """Say whether a block is an approval mechanism reporting on itself."""

    text = str(value or "").strip()
    fenced = _FENCED_JSON.match(text)
    if fenced:
        text = fenced.group("body").strip()
    if not _is_json_line(text):
        return False
    try:
        parsed = json.loads(text)
    except (ValueError, RecursionError):
        return False
    if not isinstance(parsed, dict) or "outcome" not in parsed:
        return False
    return set(parsed.keys()).issubset(_VERDICT_KEYS)


def readable_blocks(slice_value: Mapping[str, Any]) -> List[Mapping[str, Any]]:
    """Return body blocks a report may quote."""

    result: List[Mapping[str, Any]] = []
    for block in slice_value.get("blocks") or []:
        if not isinstance(block, Mapping) or block.get("context"):
            continue
        if block.get("origin") == "system_injected":
            continue
        if not str(block.get("text") or "").strip():
            continue
        result.append(block)
    return result


PROSE = "prose"
MIXED = "mixed"
MACHINE = "machine"

# What a line has to look like to be somebody talking rather than something
# being shown.  Measured on one real day: of 4.19M characters carrying the
# person's own transport role, only 1.33M were lines like these -- the rest
# were pasted diffs, logs, JSON and file dumps that arrive with the same role
# because the person pasted them.
_FENCE = re.compile(r"^\s*(?:```|~~~)")
_CJK = re.compile(r"[　-〿㐀-䶿一-鿿＀-￯]")
_SYMBOL_DENSE = re.compile(r"[{}\[\]()<>|\\/=+*_#$%^&~`@;]")
_CODE_LINE = re.compile(
    r"^(?:[+\-*][^\s]|@@|[$>%#]\s|\d+\s*[|\t]|[{}\[\]]|</?[a-zA-Z!/?]"
    r"|(?:def|class|import|from|const|let|var|function|return|export|package)\s"
    r"|[A-Za-z_][\w.]*\s*=(?!=)"
    r"|(?:ERROR|WARN|WARNING|INFO|DEBUG|Traceback|File\s\")"
    # ``ValueError: unexpected token`` is a sentence by every other measure.
    r"|[A-Za-z_][\w.]*(?:Error|Exception|Warning)\b)"
)
# A long unbroken ASCII run is a path, a hash or a URL.  The class is spelled
# out rather than using ``\S`` because CJK prose has no spaces at all and would
# otherwise match every sentence.
_ASCII_RUN = re.compile(r"[A-Za-z0-9_./\\:@#?&=%~-]{36,}")
_PROSE_SHARE = 0.6
_MIXED_SHARE = 0.2
_ELISION = "…"


def _is_json_line(text: str) -> bool:
    """Say whether the whole line is one JSON object or array.

    ``_CODE_LINE`` already rejects a line opening with a brace, but the CJK
    test below short-circuits before it, so a compact JSON payload whose string
    values hold Chinese counted as somebody talking.  That is not a rare shape:
    it is what a machine-readable verdict, a config dump and a one-line API
    response all look like, and the indented form of the same payload was
    already classified as machine.
    """

    if not (text[:1] in "{[" and text[-1:] in "}]"):
        return False
    try:
        json.loads(text)
    except (ValueError, RecursionError):
        return False
    return True


def _is_prose_line(line: str) -> bool:
    text = line.strip()
    if not text:
        return False
    if _ASCII_RUN.search(text):
        return False
    if len(_SYMBOL_DENSE.findall(text)) / len(text) > 0.12:
        return False
    if _is_json_line(text):
        return False
    if _CJK.search(text):
        return True
    if _CODE_LINE.match(text):
        return False
    words = text.split()
    return len(words) >= 4 and sum(len(word) for word in words) / len(words) < 12


def text_shape(value: Any) -> str:
    """Say whether a block is someone talking, something shown, or both.

    This is a property of the characters, not a claim about who produced them:
    ``origin`` still owns provenance.  It exists because selecting eight blocks
    out of two hundred by recency hands a report the newest paste rather than
    the request that started the work.
    """

    lines = [line for line in str(value or "").splitlines() if line.strip()]
    if not lines:
        return PROSE
    prose = 0
    fenced = False
    for line in lines:
        if _FENCE.match(line):
            fenced = not fenced
            continue
        if not fenced and _is_prose_line(line):
            prose += 1
    share = prose / len(lines)
    if share >= _PROSE_SHARE:
        return PROSE
    if share >= _MIXED_SHARE:
        return MIXED
    return MACHINE


def prose_lines(value: Any) -> List[str]:
    """Return the block's spoken lines, stripped, in order."""

    kept: List[str] = []
    fenced = False
    for line in str(value or "").splitlines():
        if _FENCE.match(line):
            fenced = not fenced
            continue
        stripped = line.strip()
        if stripped and not fenced and _is_prose_line(stripped):
            kept.append(stripped)
    return kept


def prose_excerpt(value: Any, drop: Any = frozenset()) -> Tuple[str, int]:
    """Keep the spoken lines of a block, marking where shown lines were cut.

    ``drop`` removes lines the caller has established are boilerplate for the
    whole window -- workspace rule files and skill preambles arrive inside the
    person's turn and would otherwise be the first thing every activity
    appears to be about.

    Returns the excerpt and how many lines it dropped.  An empty excerpt means
    the block says nothing of its own; the caller decides what to show instead.
    """

    kept: List[str] = []
    dropped = 0
    fenced = False
    elided = False
    for line in str(value or "").splitlines():
        if _FENCE.match(line):
            fenced = not fenced
            dropped += 1
            elided = True
            continue
        stripped = line.strip()
        if not stripped:
            continue
        if fenced or not _is_prose_line(stripped) or stripped in drop:
            dropped += 1
            elided = True
            continue
        if elided and kept:
            kept.append(_ELISION)
        kept.append(stripped)
        elided = False
    return "\n".join(kept).strip(), dropped


def injected_block_count(slice_value: Mapping[str, Any]) -> int:
    """Count body blocks written by an application rather than the person."""

    return sum(
        1
        for block in slice_value.get("blocks") or []
        if isinstance(block, Mapping)
        and not block.get("context")
        and block.get("origin") == "system_injected"
        and str(block.get("text") or "").strip()
    )


def has_execution_evidence(slice_value: Mapping[str, Any]) -> bool:
    evidence = slice_value.get("execution_evidence")
    if not isinstance(evidence, Mapping):
        return False
    return any(
        evidence.get(key) for key in ("changed_targets", "verifications", "failures")
    )


def has_readable_content(slice_value: Mapping[str, Any]) -> bool:
    if has_execution_evidence(slice_value) or slice_value.get("delegations"):
        return True
    return bool(readable_blocks(slice_value))
